Kitab/Models/Book.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Kitab.Data.Base;

namespace Kitab.Models
{
    public class Book : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string? Title { get; set; }

        [Display(Name = "Description")]
        public string? Description { get; set; }

        [Display(Name = "Price")]
        public double Price { get; set; }

        [Display(Name = "Cover")]
        public string? ImageURL { get; set; }

        [Display(Name = "Publication date")]
        public DateTime PublishedDate { get; set; }


        //Category
        //public int CategoryId { get; set; }
        //[ForeignKey("CategoryId")]
        //public Category? Category { get; set; }

        //Relationships
        public List<Category_Book>? Categories_Books { get; set; }
        public List<Author_Book>? Authors_Books { get; set; }

        //Author
        /*public int AuthorId { get; set; }
        [ForeignKey("AuthorId")]
        public Author Author { get; set; }*/

        //Publisher
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher? Publisher { get; set; }

    }
}

Kitab/Controllers/AuthorController.cs
using Kitab.Data;
using Microsoft.AspNetCore.Mvc;
using Kitab.Models;
using Microsoft.EntityFrameworkCore;
using Kitab.Data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kitab.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;
        public AuthorController(IAuthorService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allAuthors = await _service.GetAllAsync();
            return View(allAuthors);
        }

        //GET: Author/Create
        public IActionResult Create()
        {
            return View();
        }


        //see in detail what async and await does
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Author author)
        {
            if (!ModelState.IsValid)  //what is model state
            {
                return View(author);
            }
            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index)); //what does this do?
        }

        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null)
            {
                return View("NotFound");
            }
            return View(authorDetails);

        }

        //GET: Author/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null)
            {
                return View("NotFound");
            }
            return View(authorDetails);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.UpdateAsync(id, author);
            return RedirectToAction(nameof(Index));
        }

        //GET: Author/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null)
            {
                return View("NotFound");
            }
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")] //Why actionname
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Kitab/Controllers/BookController.cs
using Kitab.Data;
using Kitab.Data.Services;
using Kitab.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Kitab.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _service;

        public BookController(IBookService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            /*var allbooks = _context.Books.Include(n => n.Publisher).OrderBy(n => n.Title).ToList();*/
            //LINQ - Table join garne ani chahiteko 
            //ViewBag
            var allBooks = await _service.GetAllAsync(n => n.Publisher!);
            return View(allBooks);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allBooks = await _service.GetAllAsync(n => n.Publisher!);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allBooks.Where(n => n.Title!.ToLower().Contains(searchString.ToLower()) || n.Description!.ToLower().Contains
                    (searchString.ToLower())).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allBooks);
        }

        //GET: Book/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            return View(bookDetails);
        }

        //GET: Books/Create
        public async Task<IActionResult> Create()
        {
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
            ViewBag.Categories = new SelectList(bookDropdownsData.Categories, "Id", "Name");
            ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
                ViewBag.Categories = new SelectList(bookDropdownsData.Categories, "Id", "Name");
                ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

                return View(book);
            }

            await _service.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        //GET: Books/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null)
                return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Title = bookDetails.Title,
                Description = bookDetails.Description,
                Price = bookDetails.Price,
                PublishedDate = bookDetails.PublishedDate,
                ImageURL = bookDetails.ImageURL,
                PublisherId = bookDetails.PublisherId,
                AuthorIds = bookDetails.Authors_Books!.Select(n => n.AuthorId).ToList(),
                CategoryIds = bookDetails.Categories_Books!.Select(n => n.CategoryId).ToList()
            };
            
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
            ViewBag.Categories = new SelectList(bookDropdownsData.Categories, "Id", "Name");
            ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM book)
        {
            if (id != book.Id)
                return View("NotFound");

            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
                ViewBag.Categories = new SelectList(bookDropdownsData.Categories, "Id", "Name");
                ViewBag.Authors = new SelectList(bookDropdownsData.Authors, "Id", "FullName");

                return View(book);
            }

            await _service.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }
    }
}

Kitab/Controllers/OrderController.cs
using Kitab.Data.Cart;
using Kitab.Data.Services;
using Kitab.Data.ViewModels;
using Kitab.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Kitab.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBookService _bookService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;   
        public OrderController(IBookService bookService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _bookService = bookService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        //This method is used to redirect to specified action instead of rendering the HTML. In this case,
        //the browser receives the redirect notification and make a new request for the specified action.
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");

        }
    }
}

Kitab/Controllers/PublisherController.cs
using Kitab.Data;
using Kitab.Data.Services;
using Kitab.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Kitab.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherService _service;

        public PublisherController(IPublisherService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allPublishers = await _service.GetAllAsync();
            return View(allPublishers);
        }

        //GET: Publishers/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null)
                return NotFound();
            return View(publisherDetails);
        }

        //GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Publisher publisher)
        {
            if (!ModelState.IsValid)
                return View(publisher);

            await _service.AddAsync(publisher);
            return RedirectToAction(nameof(Index));
        }

        //GET: Publishers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null)
                return View("NotFound");
            return View(publisherDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Publisher publisher)
        {
                if (!ModelState.IsValid) return View(publisher);
                await _service.UpdateAsync(id, publisher);
                return RedirectToAction(nameof(Index));

        }

        //GET: Publishers/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null)
                return View("NotFound");
            return View(publisherDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null)
                return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

Kitab/Views/Book/Create.cshtml
@model NewBookVM
@using Kitab.Data;

@{
    ViewData["Title"] = "Create a new movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label asp-for="PublishedDate" class="control-label"></label>
                                <input asp-for="PublishedDate" type="date" class="form-control" />
                                <span asp-validation-for="PublishedDate" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <br />
                            <div>
                                <label asp-for="CategoryIds" class="control-label"></label>
                                <select asp-for="CategoryIds" class="form-control" asp-items="ViewBag.Categories" multiple></select>
                                <span asp-validation-for="CategoryIds" class="text-danger"></span>
                            </div>
                            <br />
                            <div>
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control" asp-items="ViewBag.Authors" multiple></select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <br />
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $("#ImageURL").on("change", function() {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Kitab/Views/Book/Details.cshtml
@model Book

@{
    ViewData["Title"] = "Book details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-secondary">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Title
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Title">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Publisher Name: </b>
                            <a asp-controller="Publisher" asp-action="Details" asp-route-id="@Model.PublisherId">
                                @Model.Publisher!.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Categories: </b>
                            @foreach (var category in Model.Categories_Books!)
                            {
                                <span class=" d-inline-block text-center p-1 text-light bg-primary rounded">
                                    @category.Category!.Name
                                </span>
                                       
                            }
                        </p>
                        <p class="card-text"><b>Published Date: </b>@Model.PublishedDate.ToString("dd MMMM yyyy")</p>
                        @*<p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>*@
                        <p class="card-text">
                            <b>Authors: </b>
                            <hr />
                            <div class="row">
                                <div class="d-flex align-items-center">
                                    @foreach (var author in Model.Authors_Books!)
                                    {
                                        <div class="flex-column d-inline-block text-center m-2">
                                            <img class="border-info rounded-circle" src="@author.Author!.ProfilePictureURL" style="max-width: 150px" />
                                            <br />
                                            <a asp-controller="Author" asp-action="Details" asp-route-id="@author.AuthorId">
                                                @author.Author!.FullName
                                            </a>
                                        </div>
                                    }
                                </div>
                            </div>               
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white" asp-controller="Order" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@*@await Html.PartialAsync("_CreateModel", "Book") *@

Kitab/Views/Book/Edit.cshtml
@model NewBookVM
@using Kitab.Data;

@{
    ViewData["Title"] = "Update movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label asp-for="PublishedDate" class="control-label"></label>
                                <input asp-for="PublishedDate" type="date" class="form-control" />
                                <span asp-validation-for="PublishedDate" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <br />
                            <div>
                                <label asp-for="CategoryIds" class="control-label"></label>
                                <select asp-for="CategoryIds" class="form-control" asp-items="ViewBag.Categories" multiple></select>
                                <span asp-validation-for="CategoryIds" class="text-danger"></span>
                            </div>
                            <br />
                            <div>
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control" asp-items="ViewBag.Authors" multiple></select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <br />
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        });

        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Kitab/Views/Book/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "List of Books";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-secondary">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Title
                                    @if (User.Identity!.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-end" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Publication Date: </b>@item.PublishedDate.ToString("dd MMM yy")</p>
                            @*<p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>*@

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white" asp-controller="Order" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Book") 